name: Deploy Frontend Flask App to Azure (Staging)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-flask/**'

env:
  AZURE_WEBAPP_NAME: 'NOME_DO_SEU_APP_SERVICE' # 👈 SUBSTITUA PELO NOME DO SEU APP SERVICE (WEB APP)
  PYTHON_VERSION: '3.10'
  PACKAGE_PATH: './frontend-flask'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PACKAGE_PATH }}/requirements.txt
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging Slot on Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          slot-name: 'staging'