name: Deploy Frontend Flask App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-flask/**'

env:
  AZURE_WEBAPP_NAME: 'vision-az-linux'
  PYTHON_VERSION: '3.11'
  PACKAGE_PATH: './frontend-flask'

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PACKAGE_PATH }}/requirements.txt
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          #teste para ver se funciona
          #ainda não funciona o gatilho de deploy automático
          #env: 'production' # Uncomment if you have an environment set up