name: Deploy Backend Functions to Azure (Staging)

on:
  push:
    branches:
      - main
    paths:
      - 'backend-functions/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'NOME_DA_SUA_FUNCTION_APP' # 👈 SUBSTITUA PELO NOME DA SUA FUNCTION APP
  PYTHON_VERSION: '3.10'
  PACKAGE_PATH: './backend-functions'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PACKAGE_PATH }}/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging Slot on Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          slot-name: 'staging'