name: Deploy Backend Functions to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend-functions/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'vision-az-functions-ian'
  PYTHON_VERSION: '3.11'
  PACKAGE_PATH: './backend-functions'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PACKAGE_PATH }}/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          #teste para ver se passa