name: Deploy Frontend Flask App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-flask/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'vision-az-linux'
  PYTHON_VERSION: '3.11'
  PACKAGE_PATH: './frontend-flask'

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PACKAGE_PATH }}/requirements.txt

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: 9c43f260-ce72-4dcd-ba71-cc5cc7188028
          tenant-id: 8d44b864-8582-47c1-970a-0f4f9b0dc775
          subscription-id: d5e61658-ea65-4c44-ac98-f3b1a04126e0
          auth-type: IDENTITY

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
#Forçando o deploy mesmo que não haja alterações
          enable-oryx-build: true
          scm-do-build-during-deployment: true
          slot-name: production

      - name: Logout from Azure
        run: az logout
        if: always()